dist: trusty
language: node_js
node_js:
  - 11
  
os:
  - osx

script:
  - npm run bootstrap
  - npm test

deploy:
  provider: script
  script: npm run ci-release
  on:
    branch: master
  skip_cleanup: true
