dist: trusty
language: node_js
node_js:
  - 11
  
os:
  - osx
  - linux

script:
  - npm run bootstrap
  - npm test

deploy:
  provider: script
  script: npm run dist-electron
  on:
    branch: master
  skip_cleanup: true
